In [167]:
import requests
from bs4 import BeautifulSoup
import time
import random
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from tqdm import tqdm

In [31]:
url = requests.get('https://finance.naver.com/sise/sise_market_sum.naver?sosok=0&page=1')
html = BeautifulSoup(url.text)

In [79]:
def make_table(html):
    table = html.find('table', class_ = 'type_2')
    table = pd.read_html(str(table))[0]
    del table['N']
    del table['토론실']
    table = table.dropna(subset='종목명', ignore_index=True)
    return table

In [117]:
kospi_page = int(html.find('td', class_ = 'pgRR').find('a').get('href').split('=')[-1])

In [119]:
# 퀴즈 : 모든 코스피 페이지를 가져와서 하나의 데이터 프레임 만들기

In [123]:
total = []

for i in range(1, kospi_page+1):
    url = requests.get(f'https://finance.naver.com/sise/sise_market_sum.naver?sosok=0&page={i}')
    html = BeautifulSoup(url.text)
    time.sleep(0.5)
    total.append(make_table(html))

In [147]:
kospi = pd.concat([total[i] for i in range(0, kospi_page)], ignore_index=True)
kospi['소속'] = 'KOSPI'
kospi.to_excel('kospi.xlsx', index = False)
kospi

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,소속
0,삼성전자,57500.0,상승 200,+0.35%,100.0,3432625.0,5969783.0,50.03,6034136.0,11.62,9.03,KOSPI
1,SK하이닉스,199400.0,"하락 5,600",-2.73%,5000.0,1451637.0,728002.0,55.95,1305154.0,13.92,-15.61,KOSPI
2,LG에너지솔루션,377500.0,"하락 8,000",-2.08%,500.0,883350.0,234000.0,4.54,61459.0,-243.55,6.36,KOSPI
3,삼성바이오로직스,1196000.0,"상승 45,000",+3.91%,2500.0,851241.0,71174.0,13.54,59637.0,80.88,9.12,KOSPI
4,현대차,203500.0,"하락 3,500",-1.69%,5000.0,426162.0,209416.0,37.41,226335.0,4.45,13.68,KOSPI
...,...,...,...,...,...,...,...,...,...,...,...,...
2305,TIGER 200 산업재,8245.0,하락 35,-0.42%,0.0,20.0,240.0,0.00,10771.0,NaN,NaN,KOSPI
2306,PLUS 코스닥150선물인버스,5480.0,상승 35,+0.64%,0.0,19.0,350.0,0.00,10352.0,NaN,NaN,KOSPI
2307,HANARO 글로벌백신치료제MSCI,11800.0,보합0,0.00%,0.0,18.0,150.0,0.00,79.0,NaN,NaN,KOSPI
2308,HANARO 미국애그테크,11705.0,상승 15,+0.13%,0.0,18.0,150.0,0.00,19.0,NaN,NaN,KOSPI
2309,TIGER BBIG레버리지,2075.0,하락 30,-1.43%,0.0,17.0,800.0,0.00,527.0,NaN,NaN,KOSPI

In [151]:
# 퀴즈 : 코스닥까지 가져와서 코스피 + 코스닥을 합친 하나의 데이터 프레임 만들기 per 값이 0보다 크고 10보다 작은 행만 추출

In [153]:
url = requests.get('https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page=1')
html = BeautifulSoup(url.text)

In [159]:
kosdaq_page = int(html.find('td', class_ = 'pgRR').find('a').get('href').split('=')[-1])

In [171]:
kosdaq_total = []

for i in tqdm(range(1, kosdaq_page+1)):
    url = requests.get(f'https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page={i}')
    html = BeautifulSoup(url.text)
    time.sleep(0.5 + random.random())
    kosdaq_total.append(make_table(html))

100%|███████████████████████████████████████████| 36/36 [00:51<00:00,  1.43s/it]

In [173]:
kosdaq = pd.concat([kosdaq_total[i] for i in range(0, kosdaq_page)], ignore_index=True)
kosdaq['소속'] = 'KOSDAQ'

kosdaq

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,소속
0,알테오젠,393000.0,"상승 10,000",+2.61%,500.0,209543.0,53319.0,15.82,200223.0,-7145.45,-2.27,KOSDAQ
1,에코프로비엠,135400.0,"하락 5,400",-3.84%,500.0,132423.0,97801.0,10.67,391816.0,-60.94,-0.64,KOSDAQ
2,HLB,88500.0,상승 500,+0.57%,500.0,116278.0,131387.0,22.57,666132.0,-62.15,-32.55,KOSDAQ
3,에코프로,66400.0,"하락 2,200",-3.21%,100.0,88404.0,133138.0,20.02,601265.0,-48.64,3.43,KOSDAQ
4,레인보우로보틱스,390500.0,상승 500,+0.13%,500.0,75756.0,19400.0,8.28,189194.0,-370.14,-0.93,KOSDAQ
...,...,...,...,...,...,...,...,...,...,...,...,...
1786,투비소프트,632.0,상승 2,+0.32%,500.0,63.0,9900.0,2.26,426655.0,-0.20,-41.73,KOSDAQ
1787,셀리버리,152.0,"하락 6,528",-97.72%,500.0,57.0,37183.0,2.30,16946754.0,-0.92,472.60,KOSDAQ
1788,CNH,109.0,보합0,0.00%,2500.0,41.0,37200.0,6.07,0.0,-0.04,-18.80,KOSDAQ
1789,소프트센우,7050.0,상승 140,+2.03%,200.0,25.0,357.0,0.02,107.0,-110.16,NaN,KOSDAQ
1790,대호특수강우,2820.0,하락 170,-5.69%,2500.0,24.0,848.0,0.02,1142.0,-32.79,NaN,KOSDAQ

In [175]:
df = pd.concat([kospi, kosdaq], ignore_index=True)
df

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,소속
0,삼성전자,57500.0,상승 200,+0.35%,100.0,3432625.0,5969783.0,50.03,6034136.0,11.62,9.03,KOSPI
1,SK하이닉스,199400.0,"하락 5,600",-2.73%,5000.0,1451637.0,728002.0,55.95,1305154.0,13.92,-15.61,KOSPI
2,LG에너지솔루션,377500.0,"하락 8,000",-2.08%,500.0,883350.0,234000.0,4.54,61459.0,-243.55,6.36,KOSPI
3,삼성바이오로직스,1196000.0,"상승 45,000",+3.91%,2500.0,851241.0,71174.0,13.54,59637.0,80.88,9.12,KOSPI
4,현대차,203500.0,"하락 3,500",-1.69%,5000.0,426162.0,209416.0,37.41,226335.0,4.45,13.68,KOSPI
...,...,...,...,...,...,...,...,...,...,...,...,...
4096,투비소프트,632.0,상승 2,+0.32%,500.0,63.0,9900.0,2.26,426655.0,-0.20,-41.73,KOSDAQ
4097,셀리버리,152.0,"하락 6,528",-97.72%,500.0,57.0,37183.0,2.30,16946754.0,-0.92,472.60,KOSDAQ
4098,CNH,109.0,보합0,0.00%,2500.0,41.0,37200.0,6.07,0.0,-0.04,-18.80,KOSDAQ
4099,소프트센우,7050.0,상승 140,+2.03%,200.0,25.0,357.0,0.02,107.0,-110.16,NaN,KOSDAQ
4100,대호특수강우,2820.0,하락 170,-5.69%,2500.0,24.0,848.0,0.02,1142.0,-32.79,NaN,KOSDAQ

In [181]:
df[(0 < df['PER']) & (df['PER'] < 10)].reset_index()

,index,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,소속
0,4,현대차,203500.0,"하락 3,500",-1.69%,5000.0,426162.0,209416.0,37.41,226335.0,4.45,13.68,KOSPI
1,5,삼성전자우,48200.0,상승 200,+0.42%,100.0,396631.0,822887.0,73.79,365845.0,9.74,NaN,KOSPI
2,7,기아,93900.0,"하락 1,000",-1.05%,5000.0,373415.0,397673.0,39.40,326957.0,3.90,20.44,KOSPI
3,9,KB금융,81500.0,하락 500,-0.61%,5000.0,320726.0,393528.0,75.62,260821.0,7.04,8.44,KOSPI
4,13,현대모비스,255500.0,"하락 1,000",-0.39%,5000.0,237602.0,92995.0,41.68,38558.0,6.97,8.73,KOSPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,3942,케이피티유,3495.0,하락 20,-0.57%,500.0,200.0,5726.0,0.28,702.0,9.55,6.55,KOSDAQ
619,3949,다산솔루에타,1108.0,하락 1,-0.09%,500.0,199.0,17950.0,0.54,4546.0,0.64,55.28,KOSDAQ
620,3973,디모아,3550.0,하락 5,-0.14%,500.0,175.0,4942.0,1.03,1466.0,3.08,-4.88,KOSDAQ
621,3979,씨엑스아이,57.0,상승 1,+1.79%,0.0,171.0,300578.0,0.00,609387.0,0.55,6.57,KOSDAQ
622,3982,웹스,1179.0,하락 3,-0.25%,500.0,169.0,14364.0,0.74,12975.0,7.46,2.96,KOSDAQ

In [205]:
dic = {'User-Agent' : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"}
url = requests.get('https://finance.naver.com/item/sise_day.naver?code=005930&page=1', headers = dic)
html = BeautifulSoup(url.text)

<html lang="ko">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<title>네이버페이 증권</title>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/newstock.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/common.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/finance_header.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/main.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/newstock2.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/newstock3.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/css/world.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<script language="JavaScript">
function mouseOver(obj){
  obj.style.backgroundColor="#f6f4e5";
}
function mouseOut(obj){
  obj.style.backgroundColor="#ffffff";
}
</script>
<h4 class="tlline2"><strong><span class="red03">일별</span>시세</strong></h4>
<table cellspacing="0" class="type2">
<tr>
<th>날짜</th>
<th>종가</th>
<th>전일비</th>
<th>시가</th>
<th>고가</th>
<th>저가</th>
<th>거래량</th>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.25</span></td>
<td class="num"><span class="tah p11">57,400</span></td>
<td class="num">
<em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
				100
				</span>
</td>
<td class="num"><span class="tah p11">56,600</span></td>
<td class="num"><span class="tah p11">57,800</span></td>
<td class="num"><span class="tah p11">56,500</span></td>
<td class="num"><span class="tah p11">8,285,317</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.24</span></td>
<td class="num"><span class="tah p11">57,300</span></td>
<td class="num">
<em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
				900
				</span>
</td>
<td class="num"><span class="tah p11">57,300</span></td>
<td class="num"><span class="tah p11">57,700</span></td>
<td class="num"><span class="tah p11">57,200</span></td>
<td class="num"><span class="tah p11">14,138,471</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.21</span></td>
<td class="num"><span class="tah p11">58,200</span></td>
<td class="num">
<em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
				200
				</span>
</td>
<td class="num"><span class="tah p11">58,400</span></td>
<td class="num"><span class="tah p11">58,500</span></td>
<td class="num"><span class="tah p11">57,100</span></td>
<td class="num"><span class="tah p11">22,198,428</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.20</span></td>
<td class="num"><span class="tah p11">58,400</span></td>
<td class="num">
<em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
				300
				</span>
</td>
<td class="num"><span class="tah p11">59,100</span></td>
<td class="num"><span class="tah p11">59,100</span></td>
<td class="num"><span class="tah p11">58,100</span></td>
<td class="num"><span class="tah p11">21,589,059</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.19</span></td>
<td class="num"><span class="tah p11">58,700</span></td>
<td class="num">
<em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
				1,800
				</span>
</td>
<td class="num"><span class="tah p11">57,400</span></td>
<td class="num"><span class="tah p11">58,900</span></td>
<td class="num"><span class="tah p11">57,300</span></td>
<td class="num"><span class="tah p11">25,395,151</span></td>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
<tr>
<td bgcolor="#e1e1e1" colspan="7" height="1"></td>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.18</span></td>
<td class="num"><span class="tah p11">56,900</span></td>
<td class="num">
<em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
				900
				</span>
</td>
<td class="num"><span class="tah p11">56,200</span></td>
<td class="num"><span class="tah p11">57,200</span></td>
<td class="num"><span class="tah p11">55,900</span></td>
<td class="num"><span class="tah p11">22,131,007</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.17</span></td>
<td class="num"><span class="tah p11">56,000</span></td>
<td class="num">
<em class="bu_p bu_pn"><span class="blind">보합</span></em><span class="tah p11">0</span>
</td>
<td class="num"><span class="tah p11">56,100</span></td>
<td class="num"><span class="tah p11">56,500</span></td>
<td class="num"><span class="tah p11">55,700</span></td>
<td class="num"><span class="tah p11">11,916,027</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.14</span></td>
<td class="num"><span class="tah p11">56,000</span></td>
<td class="num">
<em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
				200
				</span>
</td>
<td class="num"><span class="tah p11">56,000</span></td>
<td class="num"><span class="tah p11">57,300</span></td>
<td class="num"><span class="tah p11">56,000</span></td>
<td class="num"><span class="tah p11">23,979,779</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.13</span></td>
<td class="num"><span class="tah p11">55,800</span></td>
<td class="num">
<em class="bu_p bu_pn"><span class="blind">보합</span></em><span class="tah p11">0</span>
</td>
<td class="num"><span class="tah p11">56,100</span></td>
<td class="num"><span class="tah p11">56,400</span></td>
<td class="num"><span class="tah p11">55,600</span></td>
<td class="num"><span class="tah p11">22,448,377</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2025.02.12</span></td>
<td class="num"><span class="tah p11">55,800</span></td>
<td class="num">
<em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
				100
				</span>
</td>
<td class="num"><span class="tah p11">55,100</span></td>
<td class="num"><span class="tah p11">55,900</span></td>
<td class="num"><span class="tah p11">54,500</span></td>
<td class="num"><span class="tah p11">26,428,596</span></td>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
</table>
<!--- 페이지 네비게이션 시작--->
<table align="center" class="Nnavi" summary="페이지 네비게이션 리스트">
<caption>페이지 네비게이션</caption>
<tr>
<td class="on">
<a href="/item/sise_day.naver?code=005930&amp;page=1">1</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=2">2</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=3">3</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=4">4</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=5">5</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=6">6</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=7">7</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=8">8</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=9">9</a>
</td>
<td>
<a href="/item/sise_day.naver?code=005930&amp;page=10">10</a>
</td>
<td class="pgR">
<a href="/item/sise_day.naver?code=005930&amp;page=11">
				다음<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3"/>
</a>
</td>
<td class="pgRR">
<a href="/item/sise_day.naver?code=005930&amp;page=718">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>
</td>
</tr>
</table>
<!--- 페이지 네비게이션 끝--->
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/js/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/js/ntm.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250220171615/js/nLog.js" type="text/javascript"></script>
<script type="text/javascript">
        ;(function(){
            var eventType = "onpageshow" in window ? "pageshow" : "load";
            jindo.$Fn(function(){
                lcs_do();
            }).attach(window, eventType);
        })();
	</script>
</body>
</html>

In [211]:
table = html.find('table')
table = pd.read_html(str(table))[0].dropna()
table

            날짜       종가        전일비       시가       고가       저가         거래량
1   2025.02.25  57400.0    상승  100  56600.0  57800.0  56500.0   8285317.0
2   2025.02.24  57300.0    하락  900  57300.0  57700.0  57200.0  14138471.0
3   2025.02.21  58200.0    하락  200  58400.0  58500.0  57100.0  22198428.0
4   2025.02.20  58400.0    하락  300  59100.0  59100.0  58100.0  21589059.0
5   2025.02.19  58700.0  상승  1,800  57400.0  58900.0  57300.0  25395151.0
9   2025.02.18  56900.0    상승  900  56200.0  57200.0  55900.0  22131007.0
10  2025.02.17  56000.0        보합0  56100.0  56500.0  55700.0  11916027.0
11  2025.02.14  56000.0    상승  200  56000.0  57300.0  56000.0  23979779.0
12  2025.02.13  55800.0        보합0  56100.0  56400.0  55600.0  22448377.0
13  2025.02.12  55800.0    상승  100  55100.0  55900.0  54500.0  26428596.0