In [46]:
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By as by
from selenium.webdriver.common.keys import Keys as keys
import time
import pandas as pd

In [118]:
driver = uc.Chrome()
driver.get('https://search.naver.com/search.naver?ssc=tab.news.all&where=news&sm=tab_jum&query=%EB%8C%80%EA%B5%AC%EC%9D%80%ED%96%89')

In [120]:
body = driver.find_element(by.TAG_NAME, 'body')
for i in range(0, 10):
    time.sleep(1)
    body.send_keys(keys.PAGE_DOWN)

In [122]:
box = []
while True:
    news = driver.find_element(By.CSS_SELECTOR, "ul.list_news._infinite_list").find_elements(By.CSS_SELECTOR, "li.bx")
    for i in news:
        title = (i.find_element(By.CSS_SELECTOR, "a.news_tit").get_attribute('title'))
        summary = (i.find_element(By.CSS_SELECTOR, "div.dsc_wrap").text.strip())
        A = [title, summary]
        if A not in box:
            box.append(A)
    if len(box) == 100:
        break
    print(f"{len(box)}개 뉴스기사 수집 완료")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)

10개 뉴스기사 수집 완료
10개 뉴스기사 수집 완료
10개 뉴스기사 수집 완료
10개 뉴스기사 수집 완료
10개 뉴스기사 수집 완료
20개 뉴스기사 수집 완료
30개 뉴스기사 수집 완료
40개 뉴스기사 수집 완료
50개 뉴스기사 수집 완료
50개 뉴스기사 수집 완료
50개 뉴스기사 수집 완료
60개 뉴스기사 수집 완료
70개 뉴스기사 수집 완료
70개 뉴스기사 수집 완료
80개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료
90개 뉴스기사 수집 완료

In [287]:
driver = uc.Chrome()
driver.get('https://shopping.naver.com/fresh/directfarm/home')

In [291]:
box = []
while True:
    for i in driver.find_elements(By.CSS_SELECTOR, "li._1OKV3UfxuI"):
        title = (i.find_element(By.CSS_SELECTOR, "strong._1lxNNH5gfD").text.strip())
        price = (i.find_element(By.CSS_SELECTOR, "span._3MzrqSUlwR").text)
        star = (i.find_element(By.CSS_SELECTOR, "span._29gNnX1yLx").text.split("\n")[1])
        review = (i.find_elements(By.CSS_SELECTOR, "span._29gNnX1yLx")[1].text)
        A = [title, price, star, review]
        if A not in box:
            box.append(A)
    print(f"{len(box)}개 아이템 수집 완료")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)
    if len(box) >= 100:
        break

30개 아이템 수집 완료
50개 아이템 수집 완료
70개 아이템 수집 완료
90개 아이템 수집 완료
110개 아이템 수집 완료
130개 아이템 수집 완료

KeyboardInterrupt:

In [229]:
import requests

idx = 0
for i in driver.find_elements(by.CSS_SELECTOR, 'li._1OKV3UfxuI'):
    image = i.find_element(by.TAG_NAME, 'img')
    src = image.get_attribute('src')

    if not src:
        continue
    for j in ['.jpg', '.png', '.jpeg', '.gif']:
        if j in src:
            a = src.split('?')[0]
            f = open(f'{idx}{j}', 'wb')
            respone = requests.get(src)
            f.write(respone.content)
            f.close()
            idx += 1

In [263]:
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings('ignore')

driver = uc.Chrome()
driver.get('https://finance.naver.com/item/sise_day.naver?code=005930')

In [265]:
# 1~10페이지까지 테이블을 셀레니움으로 가져와서 하나의 데이터프레임 만들기

total = []
for i in range(1, 11):
    driver.get(f'https://finance.naver.com/item/sise_day.naver?code=005930&page={i}')
    html = BeautifulSoup(driver.page_source)
    table = html.find('table')
    table = pd.read_html(str(table))[0].dropna()
    total.append(table)

pd.concat([data for data in total], ignore_index=True)

            날짜       종가        전일비       시가       고가       저가         거래량
0   2025.02.27  56600.0        보합0  56500.0  57100.0  56400.0   7765069.0
1   2025.02.26  56600.0    하락  600  57000.0  57100.0  56100.0  18117091.0
2   2025.02.25  57200.0    하락  100  56600.0  57800.0  56500.0  14625181.0
3   2025.02.24  57300.0    하락  900  57300.0  57700.0  57200.0  14138471.0
4   2025.02.21  58200.0    하락  200  58400.0  58500.0  57100.0  22198428.0
..         ...      ...        ...      ...      ...      ...         ...
95  2024.10.07  61000.0    상승  400  60200.0  61900.0  59500.0  35066533.0
96  2024.10.04  60600.0    하락  700  61000.0  61700.0  60500.0  24247578.0
97  2024.10.02  61300.0    하락  200  60500.0  61900.0  59900.0  28473536.0
98  2024.09.30  61500.0  하락  2,700  64200.0  64300.0  61500.0  32694163.0
99  2024.09.27  64200.0    하락  500  64700.0  65400.0  64200.0  28433030.0

[100 rows x 7 columns]

In [267]:
# 1~10페이지까지 테이블을 셀레니움으로 가져와서 하나의 데이터프레임 만들기

total = []
for i in range(1, 720):
    # 페이지가 모두 뜰때까지 최대 10초를 기다려라
    driver.implicitly_wait(10)
    driver.get(f'https://finance.naver.com/item/sise_day.naver?code=005930&page={i}')
    html = BeautifulSoup(driver.page_source)
    table = html.find('table')
    table = pd.read_html(str(table))[0].dropna()
    total.append(table)

              날짜       종가        전일비       시가       고가       저가         거래량
0     2025.02.27  56600.0        보합0  56500.0  57100.0  56400.0   7775924.0
1     2025.02.26  56600.0    하락  600  57000.0  57100.0  56100.0  18117091.0
2     2025.02.25  57200.0    하락  100  56600.0  57800.0  56500.0  14625181.0
3     2025.02.24  57300.0    하락  900  57300.0  57700.0  57200.0  14138471.0
4     2025.02.21  58200.0    하락  200  58400.0  58500.0  57100.0  22198428.0
...          ...      ...        ...      ...      ...      ...         ...
7177  1996.06.29  68500.0    상승  400  68100.0  69100.0  67100.0     96710.0
7178  1996.06.28  68100.0  상승  1,200  67300.0  68500.0  67200.0    138430.0
7179  1996.06.27  66900.0    하락  800  67500.0  67700.0  66700.0    155450.0
7180  1996.06.26  67700.0    상승  200  67600.0  67900.0  66000.0    136630.0
7181  1996.06.25  67500.0        보합0  66500.0  68300.0  65600.0    112960.0

[7182 rows x 7 columns]

In [275]:
samsung = pd.concat([data for data in total], ignore_index=True)
sansung = samsung.iloc[1:]
samsung.to_excel('삼성 주가 데이터.xlsx', index = False)
samsung

              날짜       종가        전일비       시가       고가       저가         거래량
0     2025.02.27  56600.0        보합0  56500.0  57100.0  56400.0   7775924.0
1     2025.02.26  56600.0    하락  600  57000.0  57100.0  56100.0  18117091.0
2     2025.02.25  57200.0    하락  100  56600.0  57800.0  56500.0  14625181.0
3     2025.02.24  57300.0    하락  900  57300.0  57700.0  57200.0  14138471.0
4     2025.02.21  58200.0    하락  200  58400.0  58500.0  57100.0  22198428.0
...          ...      ...        ...      ...      ...      ...         ...
7177  1996.06.29  68500.0    상승  400  68100.0  69100.0  67100.0     96710.0
7178  1996.06.28  68100.0  상승  1,200  67300.0  68500.0  67200.0    138430.0
7179  1996.06.27  66900.0    하락  800  67500.0  67700.0  66700.0    155450.0
7180  1996.06.26  67700.0    상승  200  67600.0  67900.0  66000.0    136630.0
7181  1996.06.25  67500.0        보합0  66500.0  68300.0  65600.0    112960.0

[7182 rows x 7 columns]

In [285]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# 어떤 특정 요소가 뜰때까지 기다린다. (JSP)
wait = WebDriverWait(driver, 10)
A = wait.until(EC.presence_of_element_located((by.CSS_SELECTOR, 'table')))
A.click()